### ISSUE TITLE
Looking for the good version of causaldag module

### ISSUE THREAD

**Issue by fred7778** [uhlerlab/decamfound#1]
Hello,

We need the `causaldag` module to run `decamfound`.

However it seems that the `causaldag` module implementation has changed a lot since the development of `decamfound` (in particular the source code has been divided into different modules).
So I cannot use the latest `causaldag` module installed with the command `pip3 install causaldag`.

Would you know which version of the `causaldag` module was used to develop the `decamfound` source code?

Thank you very much for your help!

**Comment by csquires** [comment]
Hi, according to my virtual environment for the project, we were running the code with version 0.1a160 - I hope that one works, otherwise feel free to email me a more detailed description of the problems you're running into.

**Comment by fred7778** [comment]
Hi, indeed with causaldag version 0.1a160, everything is working!
Thank you very much for your help!
